import fs from "fs";
import keyword_extractor from "keyword-extractor";

const keywords = [
  "React",
  "Redux",
  "Vue",
  "Angular",
  "JavaScript",
  "Wordpress",
  "semantic",
  "a11y",
  "accessibility",
  "HTML",
  "CSS",
  "command line",
  "GitHub",
  "Agile",
  "PHP",
  "Python",
  "SQL",
  "clean",
  "scalable",
  "CMS",
  "Content management system",
  "DXP",
  "Digital experience",
  "Headless",
  "ECM",
  "Enterprise",
  "Digital Asset Management",
  "DAM",
  "Quality assurance",
  "Testing",
  "Next",
  "Babel",
  "SASS",
  "SCSS",
  "Webpack",
  "HTML5",
  "REST",
  "Photoshop",
  "ADA",
  "graphic design",
  "SEO",
  "Search engine optimization",
  "Moodle",
  "AWS",
  "508",
  "WCAG",
  "metadata",
  "cross-browser compatibility",
  "Drupal",
  "input validation",
  "XSS",
  "CSRF",
  "CORS",
  "FRS",
  "Functional requirement specifications",
  "Software requirement specifications",
  "Business requirements document",
  "SRS",
  "BRD",
  "Node",
  "NodeJS",
  "preprocess",
  "pre-process",
  "reusable components",
  "frontend",
  "backend",
  "Redux",
  "Umi",
  "API",
  "Java",
  "SQL",
  "DOM",
  "HTTP",
  "AJAX",
  "XHR",
  "Fetch",
  "Axios",
  "C++",
  "C program",
  "Python",
  "Rust",
  "Web services",
  "SOA",
  "service-oriented architecture",
  "EAI",
  "enterprise application integration",
  "SOAP",
  "Simple Object Access Protocol",
  "SaaS",
  "Software as a service",
  "PaaS",
  "GraphDB",
  "GraphQL",
  "Graph",
  "UI",
  "UX",
  "HCI",
  "Security",
  "XML",
  "JSON",
  "Fiori",
  "SAP",
  "OOP",
  "Object-oriented programming",
  "widget",
  "theme",
  "template",
  "WordPress Network",
  "Multisite",
  "jQuery",
  "MySQL",
  "DynamoDB",
  "Lightsail",
  "Terraform",
  "tRPC",
  "Django",
  "Flask",
  "ASP.net",
  "Spring boot",
  "Spring",
  "database",
  "documentation",
  "ASP.net",
  "Ruby",
  "Ruby on Rails",
  "Rails",
  "Object Oriented Programming",
  "Search Engine Optimization",
  "GUI",
  "ECMAscript",
  "typescript",
  "css3",
  "responsive web design",
  "functional programming",
  "mvc",
  "model-view-controller",
  "Figma",
  "Webflow",
  "Email",
  "Coldfusion",
  "Dreamweaver",
  "ActionScript",
  "Backbone",
  "Ember",
  "Less",
  "Prisma",
  "styled components",
  "CSS-in-JS",
  "Tailwind",
  "HeadlessUI",
  "Chakra",
  "Astro",
  "Cloudinary",
  "Firebase",
  "Strapi",
  "Svelte",
  "Web Speech",
  "reveal",
  "elasticsearch",
  "jsonwebtoken",
  "jwt",
  "EC2",
  "S3",
  "Shopify",
  "DVA",
  "React-hook-form",
  "Formik",
  "MaterialUI",
  "Bootstrap",
  "cookie",
  "Unity",
  "Three",
  "D3",
  "lodash",
  "Framer",
  "Scrum",
  "unit test",
  "integration test",
  "E2E",
  "cypress",
  "enzyme",
  "jest",
  "mocha",
  "chai",
  "Flux",
  "design pattern",
  "data structures",
  "algorithm",
  "leetcode",
  "hackerrank",
  "ionic",
  "flutter",
  "react native",
  "electron",
  "laminas",
  "symfony",
  "magento",
  "j2ee",
  "solidity",
  "perl",
  "linux",
  "unix",
  "emacs",
  "vim",
  "memcache",
  "redis",
  "elastic compute",
  "rds",
  "relational database services",
  "mariaDB",
  "Oracle",
  "Aurora",
  "Storybook",
  "lambda",
  "cloudfront",
  "glacier",
  "sns",
  "ebs",
  "vpc",
  "kinesis",
  "iam",
  "sqs",
  "beanstalk",
  "DynamoDB",
  "elasticache",
  "redshift",
  "sagemaker",
  "lightsail",
  "elastic file system",
  "efs",
  "cognito",
  "docker",
  "kubernetes",
  "container",
  "mongodb",
  "azure",
  "digitalocean",
  "subversion",
  "SVN",
  "mobile-first",
  "material",
  "C#",
  "analytics",
  "apache",
  "nginx",
  "CI/CD",
  "Jenkins",
  "http",
  "WWW",
  "DNS",
  "flexbox",
  "grid",
  "ES6",
  "Gitlab",
  "Bitbucket",
  "CORS",
  "OWASP",
  "XSS",
  "CSRF",
  "content security policy",
  "HTTPS",
  "TLS",
  "SSL",
  "handshake",
  "BEM",
  "PostCSS",
  "esbuild",
  "rollup",
  "parcel",
  "vite",
  "prettier",
  "eslint",
  "redux",
  "css module",
  "JSX",
  "Emotion",
  "custom element",
  "shadow DOM",
  "bulma",
  "radix",
  "testing library",
  "storage",
  "socket.io",
  "web socket",
  "prpl",
  "solid",
  "dry",
  "yagni",
  "FCP",
  "LCP",
  "singleton",
  provider, observer, module, mixin, hook, factory, CSR, SSR, hydration, tree shaking, lighthouse, internationalization, RAIL, gatsby, web assembly, wasm, blazor, go, golang, postgresql, ORM, ACID, normalization, shard, CAP, influxDB, OAuth, gRPC, CDN, monolithic, microservice, microfrontend, serverless, rabbitMQ, kafka, neo4j, caddy, trello, slack, kotlin, scala, hash, hadoop, BPM, BPEL, W3C, PWA, UML, i/o, posix, centos, ubuntu, rhel, freebsd, bash, nano, powershell, ftp, ssl, ssh, port forward, consul, istio, ansible, github action, circle CI, prometheus, grafana, datadog, loki, jaeger, new relic, google cloud, apollo, rtk, balsamiq, sketch, inkscape, illustrator, creative cloud, invision, powerpoint, word, box, dropbox, AI, ML, npm, selenium, JSP, cgi, a/b test, jsdoc, inheritance, polymorphism, abstraction, encapsulation, kernel, mobx, zustand, load balanc, clojure, MATLAB, data science, MS SQL, excel, filemaker, NLP, solr, MIME, CAPTCHA, struts, flash, thunk, react router, jasmine, yaml, handlebars, grunt, gulp, ant, .NET, entity framework, nunit, cakephp, bindows, python, voldemort, lucene, websocket, VBScript, lightning, SDLC, JPA, Hibernate, JSF, Wicket, GWT, jstl, xlst, xsd, firewall, SOAR, erlang, ocaml, scala, RDBMS, zend, Yii, visual studio, eclipse, xcode, cvs, concurrent version system, highchart, react flow, winform, linq, dapper, wcf, windows communication foundation, sqlite, saga, taskscheduler, SPA, reactive, karma, sveltekit, astro, nx, vscode, visual studio, sublime, IoT, AR, VR, MR, openxr, mrtk, oculus, openvr, stencil, cucumber, pytest, robot, jira, guru, salesforce, developer tools, appium, confluence, java server pages, common gateway interface, express, protractor, prisma, supabase, nim, godot, lisp, quik, pocketbase, surrealDB, Hugo, TensorFlow, solidjs, web3, redwood, tauri, nuxt, assembly, parallax, elixir, vite, passport, wireframe, mockup, documentation, asynchronous, closure, promise, postman, SQA, monorepo, composer, fastapi, slimphp, smarty, webgl, TDD, BDD, 
];

const inFile = "cut.json";
const outFile = "cut.json";
let jsonData: any[] = [];
let data: { [key: string]: string }[] | null = null;
if (fs.existsSync(inFile)) {
  data = JSON.parse(fs.readFileSync(inFile, { encoding: "utf-8" }));
}

if (!fs.existsSync(outFile)) {
  fs.writeFileSync(outFile, JSON.stringify(jsonData), { encoding: "utf-8" });
}

// console.log(data);

for (let i = 0; i < data!.length; i++) {
  const description = data![i].jobDescription;

  // const foundKeywords = keywords.filter((keyword) => {
  //   return description.includes(keyword);
  // });
  // console.log("INDEX: " + data![i].index, i);
  // console.log("DESCRIPTION: " + description);
  // console.log("KEYWORDS: " + foundKeywords);
}

// const appendedData = data!.filter((data, index) => index < 537 || index > 681);
// appendedData.map((data) => console.log(data.index));
// fs.writeFileSync(outFile, JSON.stringify(appendedData), {
//   encoding: "utf-8",
// });
